config/routes.rb
Rails.application.routes.draw do

  resources :pages, only: [:index, :new, :create]

  root :to => 'pages#show', :id => 'home'

  resources :pages, path: "", except: [:index, :new, :create]

end

app/models/page.rb
class Page < ActiveRecord::Base

	validates :slug, uniqueness: true, presence: true
	validates :title, uniqueness:true, presence: true

	before_validation :generate_slug

	def to_param
		slug
	end

	def generate_slug
		self.slug ||= title.parameterize
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  http_basic_authenticate_with name: ENV["HTTP_LOGIN"], password: ENV["HTTP_PW"], except: :show

  before_action :set_page, only: [:show, :edit, :update, :destroy]
  def home
	end

	def rondleiding
	end

	def kinderen
	end

	def volwasenen
	end

	def mindfullness
	end

	def contact
	end


  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1
  # PATCH/PUT /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url, notice: 'Page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find_by_slug!(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def page_params
      params.require(:page).permit(:title, :body, :language)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en"><head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta charset="utf-8">
	<!-- http://responsivewebinc.com/premium/ericka/ericka-g/ -->
	<!-- Title -->
	<title>KineVanmechelen</title>
	<!-- Description, Keywords -->
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="Wij heten U van harte welkom op onze kinesitherapie praktijk te Sint-Truiden.
	Op deze website krijgt U informatie over de werking en afspraken met de kinesist.
	Onze openingsuren zijn van maandag tot vrijdag tussen 8 uur 's morgens en 8 uur 's avonds ">
	<meta name="keywords" content="kine,kinesitherapie,kinesist,revalidatie,sint-truiden,vanmechelen,Mindfulness,fibromyalgie,Leermoeilijkheden,Gedragsmoeilijkheden,stres,Bewegingsconsulent,Hartrevalidatie">
	<meta name="author" content="Rik Vanmechelen">

	<link href="http://fonts.googleapis.com/css?family=PT+Sans:400,700,400italic" rel="stylesheet" type="text/css">
	<link href="http://fonts.googleapis.com/css?family=Oswald:400,700" rel="stylesheet" type="text/css">

	<!-- Stylesheets -->
	</head><body>
	<%= stylesheet_link_tag    "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>

	<!-- HTML5 Support for IE -->
	<!--[if lt IE 9]>
	<script src="js/html5shim.js"></script>
	<![endif]-->

	<!-- Favicon -->


<div class="wrapper">

<!-- Header starts -->

<header>
	<div class="container">
		<div class="row">
			<div class="col-sm-2 col-md-2">
				<!-- Logo and site link -->
				<div class="logo">
					<%= image_tag "logo2.png", class: "header_logo" %>
				</div>
			</div>
			<div class="col-sm-7 col-md-7">
				<!-- Logo and site link -->
				<div class="logo">
					<h1><%= link_to "Kinepraktijk Vanmechelen", root_url %><span class="color">.</span></h1>
				</div>
			</div>
			<div class="col-sm-3 col-md-3">
				<div class="list">
					<!-- Add your phone number here -->
					<div class="phone">
						<i class="icon-phone"></i> Telefoon: <a href="tel:+3211680547">011/68 05 47</a>
					</div>
					<hr>
					<div class="phone">
						<i class="icon-phone"></i> GSM: <a href="tel:+32496510547">0496/51 05 47</a>
					</div>
					<hr>
					<!-- Add your email id here -->
					<div class="email">
						<i class="icon-envelope-alt"></i> <a href="mailto:michel%40kine-vanmechelen.be?subject=via kine-vanmechelen.be" target="_blank">michel@kine-vanmechelen.be</a>
					</div>
					<hr>
					<!-- Add your address here -->
					<div class="address">
						<i class="icon-home"></i> <a href="https://www.google.com/maps/place/Kinepraktijk+Vanmechelen/@50.814251,5.165581,17z/data=!4m2!3m1!1s0x47c110d355db8f0b:0x20c71bc64d3f8427" target="_blank">Tiensesteenweg 219, 3800 St-Truiden</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</header>

<!-- Header ends -->

<!-- Navigation Starts -->

<!-- Note down the syntax before editing. It is the default twitter bootstrap navigation -->

<nav class="navbar navbar-default" role="navigation">
  <div class="navbar-inner">
		<div class="container">
		<!-- <a class="btn btn-navbar btn-default" data-toggle="collapse" data-target=".nav-collapse">
			Menu
		</a> -->
		<!-- Brand and toggle get grouped for better mobile display -->

    	<!-- <div class="navbar-header">
    	  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav">
    	    HELLO
    	  </button>
    	  <a class="btn btn-navbar" data-toggle="collapse" data-target="#main-nav">
				Menu
				</a>
    	</div> -->

    	<div class="navbar-header">
      	<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav">
      	  <span class="sr-only">Toggle navigation</span>
      	  <span class="icon-bar"></span>
      	  <span class="icon-bar"></span>
      	  <span class="icon-bar"></span>
      	</button>
    	</div>

    	<div class="collapse navbar-collapse" id="main-nav">
				<!-- Navigation links starts here -->
    	  <ul class="nav navbar-nav">
					<!-- Main menu -->
					<% Page.all.each do |page| %>
						<li><%= link_to page.title, page %></li>
					<% end %>
					<!-- Navigation with sub menu. Please note down the syntax before you need. Each and every link is important. 	-->
					<!--
					<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">Pages #1 <b class="caret"></b></a>
					-->
					<!-- Submenus
					<ul class="dropdown-menu">
					<li><a href="support.html">Support</a></li>
					<li><a href="products.html">Products</a></li>
					<li><a href="register.html">Register</a></li>
					<li><a href="login.html">Login</a></li>
					<li><a href="about.html">About</a></li>
					<li><a href="service.html">Service #1</a></li>
					<li><a href="service1.html">Service #2</a></li>
					<li><a href="pricing.html">Pricing Table</a></li>
					<li><a href="careers.html">Careers</a></li>
					<li><a href="faq.html">FAQ</a></li>
					<li><a href="team.html">Team</a></li>
					</ul>
					</li>
					-->
				</ul>
			</div>
		</div>
	</div>
</nav>

<!-- Navigation Ends -->

<!-- Content strats -->

<div class="content">
	<div class="container">
		<div class="row">
			<div class="col-sm-12 col-md-12">
				<div class="main-content">
					<%= yield %>
					<div class="bor"></div>
				</div>
			</div>
		</div>
	</div>
</div>

<!-- Content ends -->

</div>

<!-- Footer -->
<footer>
	<div class="container">
		<div class="row">
			<div class="col-sm-12 col-md-12"><hr><span class="copy">
				<!-- Copyright information. You can remove my site link. -->
				Copyright © <%= link_to "kine-vanmechelen.be", root_url %> <%= Date.current.year %></span>
				<span class="right"><%= yield :edit_link %> | <%= link_to "alle", pages_path %></span>
			</div>
		</div>
	</div>
</footer>

</body></html>

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body, class:"summernote" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/home.html.erb
<div class="row">
	<div class="col-sm-8 col-md-8">
		<h2>Welkom op de kinesitherapiepraktijk</h2>
		<p class="main-meta">Michel Vanmechelen</p>
		<p>
			Wij heten U van harte welkom op onze praktijk.
			In dit document krijgt U informatie over de werking en afspraken met de kinesist.
			Onze openingsuren zijn van maandag tot vrijdag tussen 8 uur 's morgens en 8 uur 's avonds.
			Wij helpen U liefst op de praktijk, maar als U echt niet uit de voeten kan, komen wij graag bij U op huisbezoek, eveneens op afspraak.
			Wij zijn telefonisch bereikbaar tussen 8 en 20 u. op nr.: 011/680547 of GSM. 0496/510547
			Ons e-mail adres: <%= mail_to "michel@kine&#8209;vanmechelen.be" %>
		</p>
		<h2>Wat wij behandelen en aanbieden:</h2>
		<div class="row">
			<div class="col-sm-6 col-md-6">
				<ul>
					<li>Kritische ontwikkelingsbegeleiding</li>
					<li>Mindfulness (aandachtstraining)</li>
					<li>Psychosomatische klachten</li>
					<li>Neurologische stoornissen</li>
					<li>CVS</li>
					<li>Fibromyalgie</li>
					<li>Psychomotoriek</li>
					<li>Rugschool</li>
					<li>Hartrevalidatie</li>
				</ul>
			</div>
			<div class="col-sm-6 col-md-6">
				<ul>
					<li>Gezondheidswandelingen</li>
					<li>Personal coaching</li>
					<li>Leermoeilijkheden</li>
					<li>Gedragsmoeilijkheden</li>
					<li>Stress</li>
					<li>Relaxatietechnieken</li>
					<li>Bewegingsconsulent; doorvoeld bewegen</li>
					<li>Houdingscorrecties</li>
					<li>Sportkinesitherapie</li>
				</ul>
			</div>
		</div>
		<br>
		<p>
			In geval U vragen heeft over wat er op onze praktijk gebeurt, aarzel niet het te vragen.
			Elke behandeling wordt voorafgegaan door een nauwkeurige probleemanalyse en onderzoek.
		</p>
		<p>
			Wij maken er een punt van om iedereen die zich aanmeldt binnen één week een afspraak te kunnen geven. Een acuut probleem vangen wij op binnen 48 uur.
		</p>
		<p>
			Zo U niet op een afspraak aanwezig kan zijn, gelieve dan 24 u. op voorhand af te melden. Zo U zonder afmelden afwezig bent, mogen wij de behandeling aanrekenen, doch zonder recht op terugbetaling.
		</p>
	</div>


	<div class="col-sm-4 col-md-4">
		<div class="main-box">
			<h4>Openings uren</h4>
			<h5>Enkel op afspraak</h5>
			<table width="100%">
				<thead>
					<tr>
						<td width="">&nbsp;</td>
						<td width="">Uren</td>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>Maandag</td>
						<td>8u - 21u</td>
					</tr>
					<tr>
						<td>Dinsdag</td>
						<td>8u - 21u</td>
					</tr>
					<tr>
						<td>Woensdag</td>
						<td>8u - 21u</td>
					</tr>
					<tr>
						<td>Donderdag</td>
						<td>8u - 21u</td>
					</tr>
					<tr>
						<td>Vrijdag</td>
						<td>8u - 21u</td>
					</tr>
					<tr>
						<td>Zaterdag</td>
						<td>GESLOTEN</td>
					</tr>
					<tr>
						<td>Zondag</td>
						<td>GESLOTEN</td>
					</tr>
				</tbody>
			</table>
			<div class="button">
				<a href="#"><i class="icon-calendar"></i> Vraag NU een afspraak!</a>
			</div>
		</div>
	</div>
</div>

app/views/pages/index.html.erb
<h1>Listing pages</h1>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Title</th>
      <th>url name</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr class="table-striped">
        <td><%= page.title %></td>
        <td><%= page.slug %></td>
        <td><%= link_to 'Show', page %> <%= link_to 'Edit', edit_page_path(page) %> <%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<%= raw @page.body %>

<% content_for :edit_link do %>
  <%= link_to "edit", edit_page_path(@page) %>
<% end %>